server:
  port: 8080

spring:
  application:
    name: SportsCenter

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://159.89.6.184:3306/sportscenter?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:sportscenteruser}
    password: ${SPRING_DATASOURCE_PASSWORD:YourStrongPassword123!}

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST:167.71.45.125}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: false

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:complaints.sportscenter@gmail.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:2f1d88b1c0b9dcb71c5f2d5be89801906fa2e4d84a3b19b47d3de4e154deeb71}
  expiration: ${JWT_EXPIRATION:86400000}

stripe:
  api:
    key: ${STRIPE_SECRET_KEY}

recommendation:
  service:
    url: http://127.0.0.1:8000/recommendations


